version: '3.8'

services:
  kong-database:
    image: postgres:15
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5431:5431"
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - consul-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:3.9
    command: kong migrations bootstrap --force
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
    networks:
      - consul-network
    restart: on-failure

  kong:
    image: kong:3.9
    container_name: kong
    restart: always
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: "off"  # Disable DB mode to use kong.yml
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_SSL: off
      KONG_JWT_SECRET: "M1Y1K1ZWajZtbnh0dmVqdmtEWFg5ZEQ1V2I0dHJSSFRzM3dDcGgyNzZCbjAwSkhvT0RqTjhDMzJGUEVxcHZCRnBjTFdBNjdHS2JNejdkQTE4RWNuVGZ4YUxYRmlsZWhaZnF4Y2dQUG11elM0VlVYcGVwTzdIUDVWMGdNY0NGWjVVQjV6Q29NTmFsZklxcVF5QXhRQll1R3ZybDdQd2c1WmpGbXo0aU80R0x5dUliU2ROY2V4eTlUc084UFQwOUZ4N3RNSHN3cDhPa2Qxcnl2dHJvdVo2NGlPeXFFTnF2bU9UTCtPcDdhcHdZcVZDczk1WldWZzRHcTNkbWdDUVJCUUhtVGxVSHIvN0huWi9NQnJNazZhNXIvYjh3KzNUTlQzTUYvYjNtOGhsZW1Gd1FTVXZPM2hOaG5zb296MUp1SFlrd2FRS1VROCtRM1ZVa3JSdUtQc1ZzN3dNY0VxV05wb0RvU3krcGNaY2Fj=="
      KONG_JWT_ALGORITHM: "HS256"  # JWT algoritması
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - consul-network

networks:
  consul-network:
    external: true

volumes:
  kong_data: