spring:
  application:
    name: reward-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_REWARD_SERVICE_DATABASE}?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-init-sql: "SELECT 1"
      connection-test-query: "SELECT 1"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        health-check-critical-timeout: 30s
        register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
        deregister: true
        deregister-timeout: 30s
        fail-fast: true
        prefer-ip-address: true
      config:
        enabled: false

server:
  port: 8084

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.greenearn.rewardservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.springframework.security: DEBUG

jwt:
  secret: "M1Y1K1ZWajZtbnh0dmVqdmtEWFg5ZEQ1V2I0dHJSSFRzM3dDcGgyNzZCbjAwSkhvT0RqTjhDMzJGUEVxcHZCRnBjTFdBNjdHS2JNejdkQTE4RWNuVGZ4YUxYRmlsZWhaZnF4Y2dQUG11elM0VlVYcGVwTzdIUDVWMGdNY0NGWjVVQjV6Q29NTmFsZklxcVF5QXhRQll1R3ZybDdQd2c1WmpGbXo0aU80R0x5dUliU2ROY2V4eTlUc084UFQwOUZ4N3RNSHN3cDhPa2Qxcnl2dHJvdVo2NGlPeXFFTnF2bU9UTCtPcDdhcHdZcVZDczk1WldWZzRHcTNkbWdDUVJCUUhtVGxVSHIvN0huWi9NQnJNazZhNXIvYjh3KzNUTlQzTUYvYjNtOGhsZW1Gd1FTVXZPM2hOaG5zb296MUp1SFlrd2FRS1VROCtRM1ZVa3JSdUtQc1ZzN3dNY0VxV05wb0RvU3krcGNaY2Fj"

gateway:
  url: http://http://57.151.33.67:8000

openapi:
  server:
    url: ${gateway.url}/${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.greenearn.rewardservice.controller