spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        health-check-critical-timeout: 30s
        register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
        deregister: true
        deregister-timeout: 30s
        fail-fast: true
        prefer-ip-address: true
      config:
        enabled: false

server:
  port: 8081

jwt:
  secret: "3V5+VVj6mnxtvejvkDXX9dD5Wb4trRHTs3wCph276Bn00JHoODjN8C32FPIqpfBFpcLWA67GKbMz7dA18EcnTfxaLXFilehZfqxcgPPmuzS4VUXpepO7HP4V0gMcCFZ5UB5zCoMNalfIqqQyAxQBYuGvrl7Pwg5ZjFmz4iO4GLyuIbSdNcexy9TsO8PT09Fx7tMHswp8Okd1ryvtrouZ64iOyqENqvmOTL+Op7apwYqVCs95ZWVg4Gq3dmgCQRBQHmTlUHr/7HnZ/MBrMk6a5r/r8w+3TNT3MF/b3m8hlemFwQSUvO3hNhnsooz1JuHYkwaQKUQ8+Q3VUkrRuKPsVs7wMcEqWNpoDoSy+pcZcqc="
  expiration: 86400000

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.security: DEBUG