apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  labels:
    app: auth-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
      - name: auth-postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: auth_service
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-postgres-secret
              key: password
        volumeMounts:
        - name: auth-postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: auth-postgres-data
        persistentVolumeClaim:
          claimName: auth-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-service
spec:
  selector:
    app: auth-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 