spring:
  application:
    name: challenge-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_CHALLENGE_SERVICE_DATABASE}?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-init-sql: "SELECT 1"
      connection-test-query: "SELECT 1"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        health-check-critical-timeout: 30s
        register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
        deregister: true
        deregister-timeout: 30s
        fail-fast: true
        prefer-ip-address: true
      config:
        enabled: false

server:
  port: 8085

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.greenearn.customerservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

jwt:
  secret: ${SPRING_JWT_SECRET}
  expiration: 604800000

gateway:
  url: http://57.151.33.67:8000

openapi:
  server:
    url: ${gateway.url}/${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    config-url: /api-docs/swagger-config
    url: /api-docs
  packages-to-scan: com.greenearn.challangeservice.controller