spring:
  application:
    name: mail-service
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        health-check-critical-timeout: 30s
        prefer-ip-address: true
        register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
        health-check-enabled: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_ENABLED:true}
        deregister: true
        deregister-timeout: 30s
        fail-fast: true
      config:
        enabled: ${SPRING_CLOUD_CONSUL_CONFIG_ENABLED:false}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: utf-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 30000
          connectiontimeout: 30000
          timeout: 30000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
  datasource:
    url: jdbc:postgresql://localhost:5432/mail_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

SERVER_PORT: 8082
AUTH_SERVER_PORT: 8081
#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: haydarkose86@gmail.com
EMAIL_PASSWORD: ulmm osso whea dukd
VERIFY_EMAIL_HOST: http://localhost:${AUTH_SERVER_PORT}
server:
  port: ${SERVER_PORT}