apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: green-earn
data:
  kong.yml: |
    _format_version: "1.1"
    services:
      - name: auth-service
        url: http://auth-service:8081
        routes:
          - name: auth-route
            paths:
              - /api/auth
            strip_path: false
            preserve_host: false
          - name: users-route
            paths:
              - /api/users
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
      - name: mail-service
        url: http://mail-service:8082
        routes:
          - name: mail-route
            paths:
              - /api/mail
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Accept", "Authorization", "Content-Type"]
          exposed_headers: ["Access-Control-Allow-Origin"]
          credentials: true
          max_age: 3600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: green-earn
  labels:
    app: {{ .Values.apiGateway.name }}
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
        - name: {{ .Values.apiGateway.name }}
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.apiGateway.service.port }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/etc/kong/kong.yml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_LOG_LEVEL
              value: "debug"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/kong.yml
              subPath: kong.yml
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: green-earn
  labels:
    app: {{ .Values.apiGateway.name }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.apiGateway.service.port }}
      protocol: TCP
      targetPort: {{ .Values.apiGateway.service.port }}
    - name: admin
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: {{ .Values.apiGateway.name }} 