apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "1.1"
    consumers:
      - username: auth-service
    jwt_secrets:
      - consumer: auth-service
        key: auth-service
        algorithm: HS256
        secret: {{ .Values.secretsValues.jwtSecretInKong }}
    services:
      - name: auth-service
        url: http://{{ .Values.authService.name }}:{{ .Values.authService.service.port }}
        routes:
          - name: auth-route
            paths:
              - /api/auth  
            strip_path: false
            preserve_host: false
          - name: users-route
            paths:
              - /api/users
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
          - name: auth-swagger-ui
            paths:
              - /auth-service/swagger-ui
              - /auth-service/swagger-ui.html
              - /auth-service/swagger-ui/
              - /auth-service/swagger-resources
              - /auth-service/webjars
            strip_path: true
            preserve_host: false
          - name: auth-api-docs
            paths:
              - /auth-service/api-docs
              - /auth-service/api-docs/swagger-config
            strip_path: true
            preserve_host: false
      - name: mail-service
        url: http://{{ .Values.mailService.name }}:{{ .Values.mailService.service.port }}
        routes:
          - name: mail-route
            paths:
              - /api/mail
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
      - name: customer-service
        url: http://{{ .Values.customerService.name }}:{{ .Values.customerService.service.port }}
        routes:
          - name: customer-route
            paths:
              - /api/customers
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
          - name: bottle-transactions-route
            paths:
              - /api/bottle-transactions
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
          - name: customer-swagger-ui
            paths:
              - /customer-service/swagger-ui
              - /customer-service/swagger-ui.html
            strip_path: true
            preserve_host: false
          - name: customer-api-docs
            paths:
              - /customer-service/api-docs
            strip_path: true
            preserve_host: false
      - name: reward-service
        url: http://{{ .Values.rewardService.name }}:{{ .Values.rewardService.service.port }}
        routes:
          - name: reward-route
            paths:
              - /api/rewards
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
          - name: reward-providers-route
            paths:
              - /api/reward-providers
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
          - name: reward-transactions-route
            paths:
              - /api/reward-transactions
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
          - name: reward-swagger-ui
            paths:
              - /reward-service/swagger-ui
              - /reward-service/swagger-ui.html
            strip_path: true
            preserve_host: false
          - name: reward-api-docs
            paths:
              - /reward-service/api-docs
            strip_path: true
            preserve_host: false
      - name: challenge-service
        url: http://{{ .Values.challengeService.name }}:{{ .Values.challengeService.service.port }}
        routes:
          - name: challenge-route
            paths:
              - /api/challenges
            strip_path: false
            preserve_host: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: true
                  key_claim_name: iss
    plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000"]
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Accept", "Authorization", "Content-Type"]
              exposed_headers: ["Access-Control-Allow-Origin"]
              credentials: true
              max_age: 3600