apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mailService.name }}
  labels:
    app: {{ .Values.mailService.name }}
spec:
  replicas: {{ .Values.mailService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mailService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mailService.name }}
    spec:
      containers:
      - name: {{ .Values.mailService.name }}
        image: {{ .Values.mailService.image.repository }}:{{ .Values.mailService.image.tag }}
        ports:
        - containerPort: {{ .Values.mailService.service.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_CONSUL_HOST
          value: "{{ .Values.serviceRegistry.name }}"
        - name: SPRING_CLOUD_CONSUL_PORT
          value: "{{ .Values.serviceRegistry.service.port }}"
        - name: SPRING_RABBITMQ_HOST
          value: "{{ .Values.eventBus.name }}"
        - name: SPRING_RABBITMQ_PORT
          value: "{{ .Values.eventBus.service.port }}"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        - name: EMAIL_HOST
          value: "smtp.gmail.com"
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_ID
          value: "haydarkose86@gmail.com"
        - name: EMAIL_PASSWORD
          value: "ulmm osso whea dukd"
        - name: VERIFY_EMAIL_HOST
          value: "http://auth-service:{{ .Values.authService.service.port }}"
        resources:
          {{- toYaml .Values.mailService.resources | nindent 10 }}
---
  
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mailService.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mailService.service.port }}
    targetPort: {{ .Values.mailService.service.port }}
  selector:
    app: {{ .Values.mailService.name }} 