{{- define "microservice.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .service.port }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.global.environment }}
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "{{ $.Values.serviceRegistry.name }}"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "{{ $.Values.serviceRegistry.service.port }}"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER
              value: "true"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONSUL_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_PATH
              value: "/actuator/health"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_INTERVAL
              value: "15s"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_TIMEOUT
              value: "5s"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_CRITICAL_TIMEOUT
              value: "30s"
            - name: SPRING_RABBITMQ_HOST
              value: "{{ $.Values.eventBus.name }}"
            - name: SPRING_RABBITMQ_PORT
              value: "{{ $.Values.eventBus.service.port }}"
            - name: SPRING_RABBITMQ_USERNAME
              value: "user"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "password"
            {{- if eq .name "auth-service" }}
            - name: SPRING_DATASOURCE_HOST
              value: "{{ $.Values.authService.env.SPRING_DATASOURCE_HOST }}"
            - name: SPRING_DATASOURCE_PORT
              value: "{{ $.Values.authService.env.SPRING_DATASOURCE_PORT }}"
            - name: SPRING_DATASOURCE_DATABASE
              value: "{{ $.Values.authService.env.SPRING_DATASOURCE_DATABASE }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ $.Values.authService.env.SPRING_DATASOURCE_USERNAME }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ $.Values.authService.env.SPRING_DATASOURCE_PASSWORD }}"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "{{ $.Values.authService.env.SPRING_JPA_HIBERNATE_DDL_AUTO }}"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "{{ $.Values.authService.env.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end -}} 