version: '3.8'

services:
  mail-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: haydarkose1/green-earn-mail-service:latest
    container_name: mail-service
    restart: on-failure
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER: true
      SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_ENABLED: true
      SPRING_CLOUD_CONSUL_CONFIG_ENABLED: false
    ports:
      - "8082:8082"
    networks:
      - consul-network

networks:
  consul-network:
    external: true