name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build Java Services
        run: |
          set -e

          declare -A javaServices=(
            [mail-service]="green-earn-mail-service"
            [auth-service]="green-earn-auth-service"
            [customer-service]="green-earn-customer-service"
            [reward-service]="green-earn-reward-service"
          )

          for service in "${!javaServices[@]}"; do
            if [ -f "services/$service/pom.xml" ]; then
              echo "Building $service..."
              cd "services/$service"
              mvn clean install -DskipTests
              cd ../..
            fi
          done
          
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and Push Docker images
        run: |
          set -e

          declare -A coreServices=(
            [api-gateway]="green-earn-api-gateway"
            [event-bus]="green-earn-event-bus"
            [service-registry]="green-earn-service-registry"
          )

          for service in "${!coreServices[@]}"; do
            imageName="${{ secrets.ACR_LOGIN_SERVER }}/${coreServices[$service]}:${{ github.sha }}"
            if [ -f "$service/Dockerfile" ]; then
              echo "Building and pushing $service..."
              docker build --no-cache -t "$imageName" "$service"
              docker push "$imageName"
            fi
          done

          declare -A javaServices=(
            [mail-service]="green-earn-mail-service"
            [auth-service]="green-earn-auth-service"
            [customer-service]="green-earn-customer-service"
            [reward-service]="green-earn-reward-service"
          )

          for service in "${!javaServices[@]}"; do
            imageName="${{ secrets.ACR_LOGIN_SERVER }}/${javaServices[$service]}:${{ github.sha }}"
            if [ -f "services/$service/Dockerfile" ]; then
              echo "Building and pushing $service..."
              docker build --no-cache -t "$imageName" "services/$service"
              docker push "$imageName"
            fi
          done

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Helm
        run: |
          $ErrorActionPreference = "Stop"
          $helmVersion = "3.14.2"
          $helmUrl = "https://get.helm.sh/helm-v$helmVersion-windows-amd64.zip"
          $helmZip = "helm.zip"
          $helmPath = "C:\Program Files\helm\windows-amd64"
          
          Invoke-WebRequest -Uri $helmUrl -OutFile $helmZip
          Expand-Archive -Path $helmZip -DestinationPath "C:\Program Files\helm" -Force
          
          $currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
          if ($currentPath -notlike "*$helmPath*") {
            [Environment]::SetEnvironmentVariable("Path", "$currentPath;$helmPath", "Machine")
          }
          
          $env:Path = "$env:Path;$helmPath"
          
          & "$helmPath\helm.exe" version
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Get AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          
      - name: Configure kubectl
        run: |
          $ErrorActionPreference = "Stop"
          
          # Cluster bağlantısını test et
          Write-Host "Testing cluster connection..."
          kubectl config get-contexts
          kubectl cluster-info
          
      - name: Deploy to Kubernetes
        run: |
          $ErrorActionPreference = "Stop"
          cd deployment/helm/green-earn
          
          # Önce namespace'i oluştur
          kubectl create namespace green-earn --dry-run=client -o yaml | kubectl apply -f -
          
          # PostgreSQL secret'ını oluştur
          Write-Host "Creating PostgreSQL secret..."
          kubectl create secret generic azure-postgres-secret `
            --from-literal=host=${{ secrets.AZURE_POSTGRES_HOST }} `
            --from-literal=port=${{ secrets.AZURE_POSTGRES_PORT }} `
            --from-literal=database=${{ secrets.AZURE_POSTGRES_DATABASE }} `
            --from-literal=customer-database=${{ secrets.AZURE_POSTGRES_CUSTOMER_SERVICE_DATABASE }} `
            --from-literal=reward-database=${{ secrets.AZURE_POSTGRES_REWARD_SERVICE_DATABASE }} `
            --from-literal=username=${{ secrets.AZURE_POSTGRES_USERNAME }} `
            --from-literal=password=${{ secrets.AZURE_POSTGRES_PASSWORD }} `
            -n green-earn --dry-run=client -o yaml | kubectl apply -f -
          
          # Mevcut ConfigMap'leri sil
          Write-Host "Deleting existing ConfigMaps..."
          kubectl delete configmap kong-config -n green-earn --ignore-not-found
          
          
          # Helm deployment
          & "C:\Program Files\helm\windows-amd64\helm.exe" upgrade --install green-earn . `
            --namespace green-earn `
            --create-namespace `
            --set global.environment=production `
            --set global.acrLoginServer=${{ secrets.ACR_LOGIN_SERVER }} `
            --set apiGateway.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-api-gateway `
            --set apiGateway.image.tag=${{ github.sha }} `
            --set eventBus.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-event-bus `
            --set eventBus.image.tag=${{ github.sha }} `
            --set serviceRegistry.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-service-registry `
            --set serviceRegistry.image.tag=${{ github.sha }} `
            --set authService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-auth-service `
            --set authService.image.tag=${{ github.sha }} `
            --set mailService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-mail-service `
            --set mailService.image.tag=${{ github.sha }} `
            --set customerService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-customer-service `
            --set customerService.image.tag=${{ github.sha }} `
            --set rewardService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-reward-service `
            --set rewardService.image.tag=${{ github.sha }} `
