name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Install Maven
        run: |
          $mavenVersion = "3.9.6"
          $mavenUrl = "https://dlcdn.apache.org/maven/maven-3/$mavenVersion/binaries/apache-maven-$mavenVersion-bin.zip"
          $mavenZip = "maven.zip"
          
          Invoke-WebRequest -Uri $mavenUrl -OutFile $mavenZip
          Expand-Archive -Path $mavenZip -DestinationPath "C:\Program Files" -Force
          
          $env:Path = "$env:Path;C:\Program Files\apache-maven-$mavenVersion\bin"
          
      - name: Build Java Services
        run: |
          $ErrorActionPreference = "Stop"
          
          if (Test-Path "services/mail-service/pom.xml") {
            cd services/mail-service
            & "C:\Program Files\apache-maven-3.9.6\bin\mvn.cmd" clean install -DskipTests
            cd ../..
          }
          
          if (Test-Path "services/auth-service/pom.xml") {
            cd services/auth-service
            & "C:\Program Files\apache-maven-3.9.6\bin\mvn.cmd" clean install -DskipTests
            cd ../..
          }
          
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Debug ACR Login Server
        run: |
          Write-Host "ACR Login Server: ${{ secrets.ACR_LOGIN_SERVER }}"
          
      - name: Build and Push Docker images
        run: |
          $ErrorActionPreference = "Stop"
          $acrLoginServer = "${{ secrets.ACR_LOGIN_SERVER }}"
          
          if (-not $acrLoginServer) {
            Write-Error "ACR_LOGIN_SERVER secret is not set or empty"
            exit 1
          }
          
          # Core services
          $coreServices = @{
            "api-gateway" = "green-earn-api-gateway"
            "event-bus" = "green-earn-event-bus"
            "service-registry" = "green-earn-service-registry"
          }
          
          foreach ($service in $coreServices.Keys) {
            $dockerfilePath = "$service/Dockerfile"
            if (Test-Path $dockerfilePath) {
              $content = Get-Content $dockerfilePath -Raw
              if ($content -and $content.Trim() -ne "") {
                cd "$service"
                Write-Host "Building and pushing $service..."
                $imageName = "$acrLoginServer/$($coreServices[$service]):latest"
                Write-Host "Image name: $imageName"
                docker build --no-cache -t $imageName .
                docker push $imageName
                cd ..
              }
            }
          }
          
          # Microservices
          $services = @(
            "auth-service"
            "mail-service"
          )
          
          foreach ($service in $services) {
            $dockerfilePath = "services/$service/Dockerfile"
            if (Test-Path $dockerfilePath) {
              $content = Get-Content $dockerfilePath -Raw
              if ($content -and $content.Trim() -ne "") {
                Write-Host "Building and pushing $service..."
                cd "services/$service"
                $imageName = "$acrLoginServer/green-earn-$service:latest"
                Write-Host "Image name: $imageName"
                docker build --no-cache -t $imageName .
                docker push $imageName
                cd ../..
              }
            }
          }

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Helm
        run: |
          $ErrorActionPreference = "Stop"
          $helmVersion = "3.14.2"
          $helmUrl = "https://get.helm.sh/helm-v$helmVersion-windows-amd64.zip"
          $helmZip = "helm.zip"
          $helmPath = "C:\Program Files\helm\windows-amd64"
          
          Invoke-WebRequest -Uri $helmUrl -OutFile $helmZip
          Expand-Archive -Path $helmZip -DestinationPath "C:\Program Files\helm" -Force
          
          $currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
          if ($currentPath -notlike "*$helmPath*") {
            [Environment]::SetEnvironmentVariable("Path", "$currentPath;$helmPath", "Machine")
          }
          
          $env:Path = "$env:Path;$helmPath"
          
          & "$helmPath\helm.exe" version
          
      - name: Configure kubectl
        run: |
          $ErrorActionPreference = "Stop"
          echo "${{ secrets.KUBE_CONFIG_AKS }}" > kubeconfig.yaml
          $env:KUBECONFIG = "kubeconfig.yaml"
          
      - name: Deploy to Kubernetes
        run: |
          $ErrorActionPreference = "Stop"
          cd deployment/helm/green-earn
          
          # Önce namespace'i oluştur
          kubectl create namespace green-earn --dry-run=client -o yaml | kubectl apply -f -
          
          # Helm deployment
          & "C:\Program Files\helm\windows-amd64\helm.exe" upgrade --install green-earn . `
            --namespace green-earn `
            --create-namespace `
            --set global.environment=production `
            --set global.acrLoginServer=${{ secrets.ACR_LOGIN_SERVER }} `
            --set apiGateway.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-api-gateway `
            --set eventBus.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-event-bus `
            --set serviceRegistry.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-service-registry `
            --set authService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-auth-service `
            --set mailService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-mail-service `
            --set customerService.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/green-earn-customer-service `
            --set authService.postgresql.enabled=true `
            --set authService.postgresql.auth.username=postgres `
            --set authService.postgresql.auth.password=postgres `
            --set authService.postgresql.auth.database=auth_service 